### ISSUE TITLE
go-owcrypt v1.1.7 Compilation error

### ISSUE THREAD

**Issue by MarcSky** [blocktree/go-owcrypt#6]
Hello. I have problem with compilation go-owcrypt v1.1.7.

When I try to compile my project with this library I getting the following error. I using Go 1.16 :)

```
# github.com/blocktree/go-owcrypt/bls12_381
../../vendor/github.com/blocktree/go-owcrypt/bls12_381/g1.go:92:50: cannot use &s.(*mod.Int).V (type *big.Int) as type *bls12381.Fr in argument to bls12381.NewG1().MulScalar
../../vendor/github.com/blocktree/go-owcrypt/bls12_381/g2.go:98:50: cannot use &s.(*mod.Int).V (type *big.Int) as type *bls12381.Fr in argument to bls12381.NewG2().MulScalar

```

**Comment by heshuchao** [comment]
Sorry for taking so long to reply to your issue.

This is a dependency conflicts, and I believe version 1.1.10 would work in your project.

Let me know if you got any other problems with go-owcrypt.

Sorry again!
