### ISSUE TITLE
1.1.10

### ISSUE THREAD

**Issue by langsen111** [blocktree/go-owcrypt#7]
# github.com/blocktree/go-owcrypt
../../../../go/pkg/mod/github.com/blocktree/go-owcrypt@v1.1.10/secp256k1.go:324:11: undefined: PointDecompress
../../../../go/pkg/mod/github.com/blocktree/go-owcrypt@v1.1.10/secp256r1.go:120:11: undefined: PointDecompress
../../../../go/pkg/mod/github.com/blocktree/go-owcrypt@v1.1.10/sm2_std.go:1693:11: undefined: PointDecompress
why?

**Comment by Zhangguiguang** [comment]
replace github.com/blocktree/go-owcrypt => github.com/coming-chat/go-owcrypt v1.0.3
